In [1]:
import numpy as np

In [2]:
import sympy

In [3]:
perch_length = np.array(
    [8.4, 13.7, 15.0, 16.2, 17.4, 18.0, 18.7, 19.0, 19.6, 20.0, 
     21.0, 21.0, 21.0, 21.3, 22.0, 22.0, 22.0, 22.0, 22.0, 22.5, 
     22.5, 22.7, 23.0, 23.5, 24.0, 24.0, 24.6, 25.0, 25.6, 26.5, 
     27.3, 27.5, 27.5, 27.5, 28.0, 28.7, 30.0, 32.8, 34.5, 35.0, 
     36.5, 36.0, 37.0, 37.0, 39.0, 39.0, 39.0, 40.0, 40.0, 40.0, 
     40.0, 42.0, 43.0, 43.0, 43.5, 44.0]
     )
perch_weight = np.array(
    [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 
     110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 
     130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 
     197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 
     514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 
     820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 
     1000.0, 1000.0]
     )

In [4]:
input = perch_length[:5].reshape(-1,1)
target = perch_weight[:2].reshape(-1,1)

input.shape

(5, 1)

활성화 함수와 그 미분값을 미리 정해야 한다.

In [5]:
class Activation:
  """
  데이터의 활성화 함수 연산 결과를 얻기 위함
  추가로 역전파 계산에 필요한 활성화 함수의 미분 함수
  """
  # 활성화 함수
  fx = 0
  # 활성화 함수의 미분 함수
  d_fx = 0

  def sigmoid_fun(self, input):
    """
    시그모이드 함수
    자연 상수의 지수 함수를 사용한 0~1 사이의 값 출력
    Args:
      input : 입력값
    Return:
      0~1 사이의 값
    """
    x = sympy.Symbol('x')
    result = []

    self.fx = 1/(1+np.e**(-x))

    self.d_fx = sympy.diff(self.fx, x)

    for i in range(input.shape[0]):
      result.append(self.fx.subs([(x, input[i][0])]))

    return np.array(result).reshape(-1, 1)

  def d_sigmoid_fun(self, input):
    """
    시그모이드 함수의 미분값
    arg
      input : 입력값
    return
      시그모이드 미분 함수의 계산 값
    """
    result = []

    x = sympy.Symbol('x')

    for i in range(input.shape[0]):
      result.append(self.d_fx.subs([(x,input[i][0])]))

    return np.array(result).reshape(-1, 1)

오차 함수와 그 미분값의 정의

In [6]:
class Error:
  """
  오차 함수와 오차 함수의 미분 함수를 얻을 수 있다.  
  """
  # 오차 함수
  fx = 0
  
  # 오차 함수의 미분값
  d_fx = 0
  
  def RMSE(self, target, predict):
    """
    일반적인 제곱 오차 함수
    args:
      target : 목표 변수
      predict : 예측 변수
    return:
      제곱 오차 평균 값
    """
    result = (predict - target)**2
    self.result = np.mean(result)

    t = sympy.Symbol('t')
    y = sympy.Symbol('y')

    self.fx = 1/2*((y-t)**2)

    self.d_fx = sympy.diff(self.fx, y)

    return self.result

  def d_RMSE(self, target, predict):
    """
    RMSE 의 미분 함수
    args
      target : 목표 변수
      predict : 예측 변수
    return:
      미분 함수의 계산 값
    """
    result = []

    t = sympy.Symbol('t')
    y = sympy.Symbol('y')

    for i in range(target.shape[0]):
      result.append(self.d_fx.subs([(t, target[i][0]), (y, predict[i][0])]))
    
    return np.array(result).reshape(-1, 1)


In [7]:
class Dense:
  """
  완전 연결층의 계산
  """
  # 가중치 w
  w = []

  # 편향 값 bais
  bias = []

  def cal_dense(self, input, unit, w = [], bias = []):
    """
    args
      input : 입력 데이터
      unit : 은닉층 노드의 개수
    return 
      각 가중치 별 입력 데이터와의 연산 결과
    """
    # 가중치 w의 생성
    if not w:
      w = np.random.rand(input.shape[0], unit)
    
    if not bias:
      bias = np.random.rand()

    self.w.append(w)

    self.bias.append(bias)

    return w.T.dot(input) + bias

In [8]:
class Delta:
  def cal_delta(activation, error):
    return 0

In [9]:
dense = Dense()

In [10]:
hidden_input = dense.cal_dense(input, 3)
hidden_input

array([[53.19563707],
       [41.35397791],
       [48.07734886]])

행의 개수는 입력의 개수, 열은 은닉층의 개수이다.

In [11]:
dense.w

[array([[0.35538115, 0.92417174, 0.46410683],
        [0.47913906, 0.33268205, 0.61933396],
        [0.89320646, 0.80920439, 0.57831959],
        [0.77567232, 0.60496196, 0.88791097],
        [0.99716969, 0.38869266, 0.70709974]])]

In [12]:
dense.bias

[0.3314892734574625]

In [13]:
act = Activation()

In [14]:
hidden_input

array([[53.19563707],
       [41.35397791],
       [48.07734886]])

In [15]:
hidden_output = act.sigmoid_fun(hidden_input)
hidden_output

array([[1.00000000000000],
       [1.00000000000000],
       [1.00000000000000]], dtype=object)

In [16]:
result_input = dense.cal_dense(input, 2)
result_input

array([[40.36678564],
       [22.33308955]])

In [17]:
result_output = act.sigmoid_fun(result_input)
result_output

array([[1.00000000000000],
       [0.999999999800077]], dtype=object)

In [18]:
err = Error()

In [19]:
result = err.RMSE(target, result_output)

출력층의 델타 계산
오차함수 변화량 * 활성화 함수 변화량

In [20]:
err.d_fx

-1.0*t + 1.0*y

In [21]:
d_err = err.d_RMSE(target, result_output)
d_err

array([[-4.90000000000000],
       [-31.0000000001999]], dtype=object)

In [22]:
act.d_fx

1.0*2.71828182845905**(-x)/(1 + 2.71828182845905**(-x))**2

In [23]:
d_act = act.d_sigmoid_fun(result_output)
d_act

array([[0.196611933241482],
       [0.196611933259646]], dtype=object)

In [24]:
delta = d_err * d_act
delta

array([[-0.963398472883261],
       [-6.09496993108835]], dtype=object)

In [27]:
hidden_output

array([[1.00000000000000],
       [1.00000000000000],
       [1.00000000000000]], dtype=object)

In [28]:
hidden_w_diff = hidden_output * delta.T
hidden_w_diff

array([[-0.963398472883261, -6.09496993108835],
       [-0.963398472883261, -6.09496993108835],
       [-0.963398472883261, -6.09496993108835]], dtype=object)