In [1]:
import numpy as np

In [2]:
import sympy

In [3]:
perch_length = np.array(
    [8.4, 13.7, 15.0, 16.2, 17.4, 18.0, 18.7, 19.0, 19.6, 20.0, 
     21.0, 21.0, 21.0, 21.3, 22.0, 22.0, 22.0, 22.0, 22.0, 22.5, 
     22.5, 22.7, 23.0, 23.5, 24.0, 24.0, 24.6, 25.0, 25.6, 26.5, 
     27.3, 27.5, 27.5, 27.5, 28.0, 28.7, 30.0, 32.8, 34.5, 35.0, 
     36.5, 36.0, 37.0, 37.0, 39.0, 39.0, 39.0, 40.0, 40.0, 40.0, 
     40.0, 42.0, 43.0, 43.0, 43.5, 44.0]
     )
perch_weight = np.array(
    [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 
     110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 
     130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 
     197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 
     514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 
     820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 
     1000.0, 1000.0]
     )

In [4]:
input = perch_length[:5].reshape(-1,1)
target = perch_weight[:2].reshape(-1,1)

input.shape

(5, 1)

In [5]:
class Dense:
  """
  완전 연결층의 계산
  """
  # 가중치 w
  w = []

  # 편향 값 bais
  bias = []

  def cal_dense(self, input, unit, w = [], bias = []):
    """
    args
      input : 입력 데이터
      unit : 은닉층 노드의 개수
    return 
      각 가중치 별 입력 데이터와의 연산 결과
    """
    # 가중치 w의 생성
    if not w:
      w = np.random.rand(input.shape[0], unit)
    
    if not bias:
      bias = np.random.rand()

    self.w.append(w)
    self.bias.append(bias)

    print(w)
    print("확인")

    return w.T.dot(input) + bias

In [6]:
class Layer:
  """
  MLP 의 층이 Layer에서 완성된다.
  """
  w = []
  bias = []

  units = []

  def dense(self, input, unit, w = [], bias = []):
    dense = Dense()
    
    result = dense.cal_dense(input, unit, w, bias)

    self.w.append(dense.w)
    self.bias.append(dense.bias)

    return result

  def add(self, unit):
    self.units.append(unit)

  def cal_dense(self, input, w = [], bias = []):
    layer = Layer()
    for i in self.units:
      layer.dense(input, i)
      self.bias.append(layer.bias)
      self.w.append(layer.w)


In [7]:
layer = Layer()

In [8]:
layer.add(3)

In [9]:
layer.add(2)

In [10]:
layer.units

[3, 2]

In [11]:
layer.cal_dense(input)

[[0.55361919 0.10326803 0.20183276]
 [0.77347362 0.05282373 0.14634001]
 [0.84955397 0.84928058 0.34283571]
 [0.56234416 0.49564779 0.27120385]
 [0.00839895 0.23663408 0.85563302]]
확인
[[0.53454119 0.4408105 ]
 [0.15770347 0.33802785]
 [0.45785773 0.16992285]
 [0.79126823 0.74915364]
 [0.82121428 0.69285917]]
확인


In [12]:
layer.w

[[array([[0.55361919, 0.10326803, 0.20183276],
         [0.77347362, 0.05282373, 0.14634001],
         [0.84955397, 0.84928058, 0.34283571],
         [0.56234416, 0.49564779, 0.27120385],
         [0.00839895, 0.23663408, 0.85563302]]),
  array([[0.53454119, 0.4408105 ],
         [0.15770347, 0.33802785],
         [0.45785773, 0.16992285],
         [0.79126823, 0.74915364],
         [0.82121428, 0.69285917]])],
 [...],
 [array([[0.55361919, 0.10326803, 0.20183276],
         [0.77347362, 0.05282373, 0.14634001],
         [0.84955397, 0.84928058, 0.34283571],
         [0.56234416, 0.49564779, 0.27120385],
         [0.00839895, 0.23663408, 0.85563302]]),
  array([[0.53454119, 0.4408105 ],
         [0.15770347, 0.33802785],
         [0.45785773, 0.16992285],
         [0.79126823, 0.74915364],
         [0.82121428, 0.69285917]])],
 [...]]

In [13]:
layer.bias

[[0.6356708794779734, 0.9297794124820543],
 [...],
 [0.6356708794779734, 0.9297794124820543],
 [...]]

In [16]:
len(layer.bias)

4

In [17]:
len(layer.w)

4