In [1]:
import numpy as np

입력값과 임의의 타겟값의 지정

In [2]:
data = np.array(([1],[2],[3]))
data

array([[1],
       [2],
       [3]])

In [3]:
target = np.array(([0.5],[0.1]))
target

array([[0.5],
       [0.1]])

임의의 가중치 지정

In [4]:
w = []

In [5]:
w.append(np.array([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]]))

In [6]:
w.append(np.array([[0.7, 0.8], [0.9, 0.1]]))

In [7]:
w

[array([[0.1, 0.2],
        [0.3, 0.4],
        [0.5, 0.6]]), array([[0.7, 0.8],
        [0.9, 0.1]])]

In [8]:
b = []

In [9]:
b.append(np.array([[0.5]]))

In [10]:
b.append(np.array([[0.3]]))

In [11]:
b

[array([[0.5]]), array([[0.3]])]

In [12]:
class cost_function:
  # 예측값
  predict = []
  # 타겟값
  target = []

  # 오차 제곱합
  def errer_squared_sum(self, predict, target):
    self.predict = predict
    self.target = target

    error_cost = np.sum(0.5*((predict - target)**2))
    return error_cost

  # 오차 제곱합 미분 함수
  def diff_error_squared_sum(self):
    return self.predict - self.target

In [13]:
class activation:
  def sigmoid(self, x):
    return 1 / (1+np.e**-x)
  
  def sigmoid_diff(self, x):
  # 활성화 함수의 계산 값이 예측값이다.
    return x * (1 - x)

In [14]:
class MLP:
  input_data = []
  weight = []
  bias = []
    
  node_input = []
  node_output = []

  predict = []
  target = []

  delta = []

  cost_function1 = cost_function()
  activation1 = activation()

  weight_update = []
  
  #순전파 계산산
  def forward_cal(self, input, w, b):
    #가중치와 편향 값의 지정
    self.weight = w
    self.bias = b
        
    #데이터 입력값이 입력층의 노드의 출력이 됨
    output = input
    self.node_output.append(output)
        
    #3차원 배열 형태의 가중치의 층 갯수만큼 순전파 연산의 반복
    for i in range(len(w)):
      #가중치와 노드 출력의 행렬곱연산, 편향값 덧셈
      hidden_input = w[i].T @ output + b[i][0]
            
      #노드 입력과 활성화 함수 연산을 통한 노드 출력 계산
      output = self.activation1.sigmoid(hidden_input)
            
      self.node_output.append(output)
      
      #최종 연산 결과, 예측값의 저장
      self.predict = output

    return output

  def cost_function(self, target):
    self.target = target
    return self.cost_function1.errer_squared_sum(self.predict, target)

  #델타(노드 변화량에 대한 비용 함수의 변화량 계산)
  def cal_delta(self):
    #출력층 노드의 변화량에 대한 오차 함수의 변화량 계산
    delta = (self.cost_function1.diff_error_squared_sum() * self.activation1.sigmoid_diff(self.predict))
    self.delta.append(delta)

    #이전층 노드의 delta 값 계산과 함께, 가중치 변화량에 대한 비용 함수의 변화량을 계산한다.
    for i in range(len(self.node_output) - 2, -1, -1):

      weight_update = (delta @ self.node_output[i].T).T
      self.weight_update.append(weight_update)
      delta = self.weight[i]@delta
      delta = delta * self.activation1.sigmoid_diff(self.node_output[i])
      self.delta.append(delta)
    
  def update_weight(self, learning_rate):
    self.weight_update = self.weight_update[::-1]
    for i in range(len(self.weight)):
      weight = self.weight[i]
      weight_update = self.weight_update[i]

      self.weight[i] = weight - weight_update * learning_rate


In [15]:
mlp = MLP()

In [16]:
result = mlp.forward_cal(data, w, b)
result

array([[0.86103399],
       [0.75879129]])

In [17]:
mlp.cost_function(target)

0.2821757530435978

In [18]:
mlp.cal_delta()

In [19]:
mlp.delta

[array([[0.04319933],
        [0.12057664]]), array([[0.00747633],
        [0.00174744]]), array([[ 0.        ],
        [-0.00588375],
        [-0.02871977]])]

In [20]:
mlp.weight

[array([[0.1, 0.2],
        [0.3, 0.4],
        [0.5, 0.6]]), array([[0.7, 0.8],
        [0.9, 0.1]])]

In [21]:
mlp.weight_update

[array([[0.04047892, 0.11298352],
        [0.04166268, 0.11628758]]), array([[0.00747633, 0.00174744],
        [0.01495265, 0.00349488],
        [0.02242898, 0.00524232]])]

In [22]:
mlp.delta

[array([[0.04319933],
        [0.12057664]]), array([[0.00747633],
        [0.00174744]]), array([[ 0.        ],
        [-0.00588375],
        [-0.02871977]])]

In [23]:
mlp.update_weight(0.01)

In [24]:
mlp.weight

[array([[0.09992524, 0.19998253],
        [0.29985047, 0.39996505],
        [0.49977571, 0.59994758]]), array([[0.69959521, 0.79887016],
        [0.89958337, 0.09883712]])]

In [25]:
mlp2 = MLP()

In [28]:
mlp2.forward_cal(data, mlp.weight, mlp.bias)

array([[0.86093442],
       [0.75838284]])

In [30]:
mlp2.cost_function(target)

0.28187080575359613