In [2]:
import numpy as np

입력값과 임의의 타겟값의 지정

In [3]:
data = np.array(([1],[2],[3]))
data

array([[1],
       [2],
       [3]])

In [4]:
target = np.array(([0.5],[0.1]))
target

array([[0.5],
       [0.1]])

임의의 가중치 지정

In [5]:
w1 = [[[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]]]
w1

[[[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]]]

In [6]:
w2 = [[0.7, 0.8], [0.9, 0.1]]
w2

[[0.7, 0.8], [0.9, 0.1]]

In [7]:
w1.append(w2)
w1

[[[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]], [[0.7, 0.8], [0.9, 0.1]]]

In [8]:
w = w1
w

[[[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]], [[0.7, 0.8], [0.9, 0.1]]]

In [9]:
b = [[0.5],[0.3]]
b

[[0.5], [0.3]]

In [21]:
class cost_function:
  def errer_squared_sum(self, predict, target):
    error_cost = np.sum(0.5*((predict - target)**2))
    return error_cost

In [22]:
class activation:
  def sigmoid(self, x):
    return 1 / (1+np.e**-x)
  
  def sigmoid_diff(self, x):
  # 활성화 함수의 계산 값이 예측값이다.
    return x * (1 - x)

In [23]:
class MLP:
  input_data = []
  weight = []
  bias = []
    
  node_input = []
  node_output = []

  predict = []

  cost_function1 = cost_function()
  activation1 = activation()
    
  def forward_cal(self, input, w, b):
    #가중치와 편향 값의 지정
    self.w = w
    self.b = b
        
    #데이터 입력값이 입력층의 노드의 출력이 됨
    output = input
    self.node_output.append(output)
        
    #3차원 배열 형태의 가중치의 층 갯수만큼 순전파 연산의 반복
    for i in range(len(w)):
      #행렬곱 연산을 위한 numpy_array 변환
      w_numpy = np.array(w[i])
            
      #가중치와 노드 출력의 행렬곱연산, 편향값 덧셈
      hidden_input = w_numpy.T @ output + b[i][0]
            
      #노드 입력과 활성화 함수 연산을 통한 노드 출력 계산
      output = self.activation1.sigmoid(hidden_input)
            
      self.node_output.append(output)
      
      #최종 연산 결과, 예측값의 저장
      self.predict = output

    return output

  def cost_function(self, target):
    a = self.cost_function1.errer_squared_sum(self.predict, target)
    return a

In [24]:
mlp = MLP()

In [25]:
result = mlp.forward_cal(data, w, b)
result

array([[0.86103399],
       [0.75879129]])

In [26]:
mlp.cost_function(target)

0.2821757530435978