In [1]:
import numpy as np

입력값과 임의의 타겟값의 지정

In [2]:
data = np.array(([1],[2],[3]))
data

array([[1],
       [2],
       [3]])

In [3]:
target = np.array(([0.5],[0.1]))
target

array([[0.5],
       [0.1]])

임의의 가중치 지정

In [4]:
w = []

In [5]:
w.append(np.array([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]]))

In [6]:
w.append(np.array([[0.7, 0.8], [0.9, 0.1]]))

In [7]:
b = []

In [8]:
b.append(np.array([[0.5]]))

In [9]:
b.append(np.array([[0.3]]))

In [10]:
# 비용 함수 클래스, 비용 함수의 종류에 따라 다른 클래스 내 함수를 사용한다.
class cost_function:
  # 예측값
  predict = []
  # 타겟값
  target = []
  # 비용 함수값
  error_cost = []

  # 오차 제곱합
  def errer_squared_sum(self, predict, target):
    self.predict = predict
    self.target = target

    self.error_cost = np.sum(0.5*((predict - target)**2))
    return self.error_cost

  # 오차 제곱합 미분 함수
  def diff_error_squared_sum(self):
    return self.predict - self.target

In [11]:
# 활성화 함수
class activation_function:
  # 시그모이드 함수
  def sigmoid(self, x):
    return 1 / (1+np.e**-x)
  
  # 시그모이드 함수의 미분 함수
  def sigmoid_diff(self, x):
    return x * (1 - x)

In [12]:
class MLP:
  #입력값
  input_data = []
  #가중치
  weight = []
  #편향값
  bias = []
    
  # 각 층별 노드들의 입력
  node_input = []
  # 각 층별 노드들의 출력
  node_output = []

  # 순전파 연산 결과, 예상값
  predict = []
  # 타겟, 목푯값
  target = []

  # 각 층의 델타 값의 저장
  delta = []

  # 비용 함수
  cost = cost_function()

  # 활성화 함수
  activation = activation_function()

  # 가중치 업데이트 크기
  weight_update = []
  
  #순전파 계산산
  def forward_cal(self, input, w, b):
    # 입력값의 저장
    self.input_data = input
    
    #가중치와 편향 값의 지정
    self.weight = w
    self.bias = b

    #데이터 입력값이 입력층의 노드의 출력이 됨
    self.node_output.append(self.input_data)
        
    #3차원 배열 형태의 가중치의 층 갯수만큼 순전파 연산의 반복
    for i in range(len(self.weight)):
      #가중치와 노드 출력의 행렬곱연산, 편향값 덧셈
      hidden_input = w[i].T @ self.node_output[i] + b[i][0]
            
      #노드 입력과 활성화 함수 연산을 통한 노드 출력 계산
      output = self.activation.sigmoid(hidden_input)
            
      #노드 출력의 저장(델타 값의 계산을 위해)
      self.node_output.append(output)
      
    #최종 연산 결과, 예측값의 저장
    self.predict = output

    return output

  def cost_function(self, target):
    self.target = target
    return self.cost.errer_squared_sum(self.predict, target)

  #델타(노드 변화량에 대한 비용 함수의 변화량) 계산산
  def cal_delta(self):
    #출력층 노드의 변화량에 대한 오차 함수의 변화량 계산
    delta = (self.cost.diff_error_squared_sum() * self.activation.sigmoid_diff(self.predict))
    self.delta.append(delta)

    #이전층 노드의 delta 값 계산과 함께, 가중치 변화량에 대한 비용 함수의 변화량을 계산한다.
    for i in range(len(self.node_output) - 2, -1, -1):

      weight_update = (delta @ self.node_output[i].T).T
      self.weight_update.append(weight_update)
      delta = self.weight[i]@delta
      delta = delta * self.activation.sigmoid_diff(self.node_output[i])
      self.delta.append(delta)
  
  # 가중치 업데이트 크기 계산 함수
  def update_weight(self, learning_rate):
    # 거꾸로 계산된 가중치 업데이트 배열을 뒤집어준다.
    self.weight_update = self.weight_update[::-1]
    for i in range(len(self.weight)):
      weight = self.weight[i]
      weight_update = self.weight_update[i]

      self.weight[i] = weight - weight_update * learning_rate

  # 반복 학습을 위한 함수
  def forward_cal_iterations(self, iterations, learning_rate):
    self.node_output.append(self.input_data)
    
    # 지정한 반복 횟수만큼 학습 시행
    for i in range(iterations):
      # 순전파 계산 수행
      for j in range(len(self.weight)):
        hidden_input = self.weight[j].T @ self.node_output[j] + self.bias[j][0]

        output = self.activation.sigmoid(hidden_input)

        self.node_output.append(output)
      
      self.predict = output
      print(self.cost_function(self.target), "비용 함수값")
      self.cal_delta
      self.weight_update = self.weight_update[::-1]
      self.weight_update
      self.update_weight(learning_rate)





In [13]:
mlp = MLP()

In [14]:
result = mlp.forward_cal(data, w, b)
result

array([[0.86103399],
       [0.75879129]])

In [15]:
mlp.cost_function(target)

0.2821757530435978

In [16]:
mlp.cal_delta()

In [17]:
mlp.delta

[array([[0.04319933],
        [0.12057664]]), array([[0.00747633],
        [0.00174744]]), array([[ 0.        ],
        [-0.00588375],
        [-0.02871977]])]

In [18]:
mlp.weight

[array([[0.1, 0.2],
        [0.3, 0.4],
        [0.5, 0.6]]), array([[0.7, 0.8],
        [0.9, 0.1]])]

In [19]:
mlp.weight_update

[array([[0.04047892, 0.11298352],
        [0.04166268, 0.11628758]]), array([[0.00747633, 0.00174744],
        [0.01495265, 0.00349488],
        [0.02242898, 0.00524232]])]

In [20]:
mlp.delta

[array([[0.04319933],
        [0.12057664]]), array([[0.00747633],
        [0.00174744]]), array([[ 0.        ],
        [-0.00588375],
        [-0.02871977]])]

In [21]:
mlp.update_weight(0.01)

In [22]:
mlp.weight

[array([[0.09992524, 0.19998253],
        [0.29985047, 0.39996505],
        [0.49977571, 0.59994758]]), array([[0.69959521, 0.79887016],
        [0.89958337, 0.09883712]])]

In [23]:
mlp.forward_cal_iterations(10, 0.01)

0.2818790553005689 비용 함수값
0.28158221051900706 비용 함수값
0.28128521937260265 비용 함수값
0.28098808253705665 비용 함수값
0.28069080069007774 비용 함수값
0.28039337451137913 비용 함수값
0.2800958046826753 비용 함수값
0.27979809188767857 비용 함수값
0.27950023681209507 비용 함수값
0.2792022401436223 비용 함수값


In [24]:
mlp.forward_cal_iterations(100, 0.01)

0.27890410257194553 비용 함수값
0.27860582478873314 비용 함수값
0.27830740748763433 비용 함수값
0.2780088513642749 비용 함수값
0.27771015711625363 비용 함수값
0.2774113254431389 비용 함수값
0.27711235704646453 비용 함수값
0.2768132526297263 비용 함수값
0.2765140128983779 비용 함수값
0.2762146385598271 비용 함수값
0.2759151303234323 비용 함수값
0.2756154889004978 비용 함수값
0.27531571500427043 비용 함수값
0.2750158093499355 비용 함수값
0.27471577265461206 비용 함수값
0.27441560563734957 비용 함수값
0.27411530901912323 비용 함수값
0.27381488352283045 비용 함수값
0.27351432987328556 비용 함수값
0.2732136487972165 비용 함수값
0.2729128410232599 비용 함수값
0.2726119072819569 비용 함수값
0.2723108483057488 비용 함수값
0.2720096648289729 비용 함수값
0.27170835758785694 비용 함수값
0.27140692732051575 비용 함수값
0.27110537476694624 비용 함수값
0.2708037006690226 비용 함수값
0.27050190577049166 비용 함수값
0.27019999081696844 비용 함수값
0.2698979565559314 비용 함수값
0.269595803736717 비용 함수값
0.26929353311051596 비용 함수값
0.2689911454303673 비용 함수값
0.2686886414511543 비용 함수값
0.2683860219295987 비용 함수값
0.2680832876242566 비용 함수값
0.26778043929551254 비용

In [25]:
mlp.forward_cal_iterations(1000, 0.01)

0.24850560167853578 비용 함수값
0.2481971168271076 비용 함수값
0.2478885710236959 비용 함수값
0.24757996513610106 비용 함수값
0.24727130003351797 비용 함수값
0.24696257658652787 비용 함수값
0.24665379566709061 비용 함수값
0.24634495814853663 비용 함수값
0.24603606490555865 비용 함수값
0.24572711681420434 비용 함수값
0.24541811475186737 비용 함수값
0.24510905959728005 비용 함수값
0.2447999522305045 비용 함수값
0.24449079353292485 비용 함수값
0.24418158438723925 비용 함수값
0.24387232567745062 비용 함수값
0.2435630182888593 비용 함수값
0.24325366310805424 비용 함수값
0.24294426102290462 비용 함수값
0.24263481292255168 비용 함수값
0.2423253196973998 비용 함수값
0.24201578223910833 비용 함수값
0.24170620144058297 비용 함수값
0.24139657819596683 비용 함수값
0.24108691340063243 비용 함수값
0.24077720795117258 비용 함수값
0.24046746274539157 비용 함수값
0.24015767868229698 비용 함수값
0.2398478566620903 비용 함수값
0.23953799758615846 비용 함수값
0.23922810235706488 비용 함수값
0.2389181718785405 비용 함수값
0.23860820705547503 비용 함수값
0.23829820879390773 비용 함수값
0.23798817800101868 비용 함수값
0.2376781155851193 비용 함수값
0.2373680224556441 비용 함수값
0.23705789

In [26]:
mlp.forward_cal_iterations(1000, 0.01)

0.03170413773411788 비용 함수값
0.03162544255494573 비용 함수값
0.03154695169673059 비용 함수값
0.031468664684845805 비용 함수값
0.031390581044977335 비용 함수값
0.03131270030312881 비용 함수값
0.031235021985626454 비용 함수값
0.031157545619123782 비용 함수값
0.031080270730606784 비용 함수값
0.031003196847398384 비용 함수값
0.030926323497163535 비용 함수값
0.030849650207913852 비용 함수값
0.030773176508012402 비용 함수값
0.03069690192617834 비용 함수값
0.030620825991491806 비용 함수값
0.030544948233398407 비용 함수값
0.030469268181713978 비용 함수값
0.030393785366629143 비용 함수값
0.030318499318713974 비용 함수값
0.030243409568922436 비용 함수값
0.030168515648597134 비용 함수값
0.03009381708947363 비용 함수값
0.030019313423685065 비용 함수값
0.029945004183766562 비용 함수값
0.029870888902659723 비용 함수값
0.029796967113716964 비용 함수값
0.029723238350706012 비용 함수값
0.029649702147814178 비용 함수값
0.02957635803965271 비용 함수값
0.0295032055612612 비용 함수값
0.029430244248111706 비용 함수값
0.029357473636113195 비용 함수값
0.02928489326161565 비용 함수값
0.029212502661414272 비용 함수값
0.029140301372753846 비용 함수값
0.029068288933332652 비용 함수값
0.

In [27]:
mlp.forward_cal_iterations(1000, 0.01)

0.0033616029109251656 비용 함수값
0.003357649377772989 비용 함수값
0.003353727818058883 비용 함수값
0.0033498382339340457 비용 함수값
0.0033459806275948755 비용 함수값
0.003342155001282482 비용 함수값
0.0033383613572822227 비용 함수값
0.0033345996979232766 비용 함수값
0.0033308700255781404 비용 함수값
0.003327172342662191 비용 함수값
0.0033235066516332317 비용 함수값
0.0033198729549910448 비용 함수값
0.0033162712552769046 비용 함수값
0.003312701555073167 비용 함수값
0.003309163857002799 비용 함수값
0.0033056581637289388 비용 함수값
0.0033021844779544496 비용 함수값
0.0032987428024214634 비용 함수값
0.0032953331399109536 비용 함수값
0.0032919554932422978 비용 함수값
0.0032886098652728105 비용 함수값
0.003285296258897349 비용 함수값
0.003282014677047837 비용 함수값
0.0032787651226928558 비용 함수값
0.003275547598837202 비용 함수값
0.003272362108521464 비용 함수값
0.0032692086548215806 비용 함수값
0.0032660872408484315 비용 함수값
0.003262997869747399 비용 함수값
0.003259940544697938 비용 함수값
0.003256915268913176 비용 함수값
0.003253922045639474 비용 함수값
0.003250960878156011 비용 함수값
0.0032480317697743764 비용 함수값
0.0032451347238381368 비용 함수값


In [28]:
mlp.weight

[array([[-0.13258852,  0.14563712],
        [-0.16517705,  0.29127425],
        [-0.19776557,  0.43691137]]), array([[-0.55929921, -2.71491738],
        [-0.39612583, -3.51770673]])]