In [165]:
import numpy as np

입력값과 임의의 타겟값의 지정

In [166]:
data = np.array(([1],[2],[3]))
data

array([[1],
       [2],
       [3]])

In [167]:
target = np.array(([0.5],[0.1]))
target

array([[0.5],
       [0.1]])

임의의 가중치 지정

In [168]:
w = []

In [169]:
w.append(np.array([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]]))

In [170]:
w.append(np.array([[0.7, 0.8], [0.9, 0.1]]))

In [171]:
w

[array([[0.1, 0.2],
        [0.3, 0.4],
        [0.5, 0.6]]), array([[0.7, 0.8],
        [0.9, 0.1]])]

In [172]:
b = []

In [173]:
b.append(np.array([[0.5]]))

In [174]:
b.append(np.array([[0.3]]))

In [175]:
b

[array([[0.5]]), array([[0.3]])]

In [176]:
class cost_function:
  # 예측값
  predict = []
  # 타겟값
  target = []

  # 오차 제곱합
  def errer_squared_sum(self, predict, target):
    self.predict = predict
    self.target = target

    error_cost = np.sum(0.5*((predict - target)**2))
    return error_cost

  # 오차 제곱합 미분 함수
  def diff_error_squared_sum(self):
    return self.predict - self.target

In [177]:
class activation:
  def sigmoid(self, x):
    return 1 / (1+np.e**-x)
  
  def sigmoid_diff(self, x):
  # 활성화 함수의 계산 값이 예측값이다.
    return x * (1 - x)

In [178]:
class MLP:
  input_data = []
  weight = []
  bias = []
    
  node_input = []
  node_output = []

  predict = []
  target = []

  delta = []

  cost_function1 = cost_function()
  activation1 = activation()

  weight_update = []
  
  #순전파 계산산
  def forward_cal(self, input, w, b):
    #가중치와 편향 값의 지정
    self.weight = w
    self.bias = b
        
    #데이터 입력값이 입력층의 노드의 출력이 됨
    output = input
    self.node_output.append(output)
        
    #3차원 배열 형태의 가중치의 층 갯수만큼 순전파 연산의 반복
    for i in range(len(w)):
      #행렬곱 연산을 위한 numpy_array 변환
      w_numpy = np.array(w[i])
            
      #가중치와 노드 출력의 행렬곱연산, 편향값 덧셈
      hidden_input = w_numpy.T @ output + b[i][0]
            
      #노드 입력과 활성화 함수 연산을 통한 노드 출력 계산
      output = self.activation1.sigmoid(hidden_input)
            
      self.node_output.append(output)
      
      #최종 연산 결과, 예측값의 저장
      self.predict = output

    return output

  def cost_function(self, target):
    self.target = target
    return self.cost_function1.errer_squared_sum(self.predict, target)

  #델타(노드 변화량에 대한 비용 함수의 변화량 계산)
  def cal_delta(self):
    #출력층 노드의 변화량에 대한 오차 함수의 변화량 계산
    delta = (self.cost_function1.diff_error_squared_sum() * self.activation1.sigmoid_diff(self.predict))
    self.delta.append(delta)

    for i in range(len(self.node_output) - 2, -1, -1):
      weight_update = delta * self.node_output[i]
      self.weight_update.append(weight_update)
      print(weight_update, "확인")
      delta = delta * self.weight[i]
      print(delta, "확인2")
      


In [179]:
mlp = MLP()

In [180]:
result = mlp.forward_cal(data, w, b)
result

array([[0.86103399],
       [0.75879129]])

In [181]:
mlp.cost_function(target)

0.2821757530435978

In [182]:
mlp.cal_delta()

[[0.04047892]
 [0.11628758]] 확인
[[0.03023953 0.03455946]
 [0.10851897 0.01205766]] 확인2


ValueError: ignored

In [ ]:
mlp.delta

In [ ]:
mlp.weight

In [ ]:
mlp.delta[0] * mlp.node_output[1]

In [ ]:
mlp.node_output

In [ ]:
mlp.node_output[1]

In [ ]:
for i in range(len(mlp.node_output)-2, -1, -1):
  print(i)