In [66]:
import numpy as np

In [67]:
import sympy

In [68]:
perch_length = np.array(
    [8.4, 13.7, 15.0, 16.2, 17.4, 18.0, 18.7, 19.0, 19.6, 20.0, 
     21.0, 21.0, 21.0, 21.3, 22.0, 22.0, 22.0, 22.0, 22.0, 22.5, 
     22.5, 22.7, 23.0, 23.5, 24.0, 24.0, 24.6, 25.0, 25.6, 26.5, 
     27.3, 27.5, 27.5, 27.5, 28.0, 28.7, 30.0, 32.8, 34.5, 35.0, 
     36.5, 36.0, 37.0, 37.0, 39.0, 39.0, 39.0, 40.0, 40.0, 40.0, 
     40.0, 42.0, 43.0, 43.0, 43.5, 44.0]
     )
perch_weight = np.array(
    [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 
     110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 
     130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 
     197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 
     514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 
     820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 
     1000.0, 1000.0]
     )

In [69]:
input = perch_length[:5].reshape(-1,1)
target = perch_weight[:2].reshape(-1,1)

input.shape

(5, 1)

활성화 함수와 그 미분값을 미리 정해야 한다.

In [70]:
class Activation:
  """
  데이터의 활성화 함수 연산 결과를 얻기 위함
  추가로 역전파 계산에 필요한 활성화 함수의 미분 함수
  """
  # 활성화 함수
  fx = 0
  # 활성화 함수의 미분 함수
  d_fx = 0

  def sigmoid_fun(self, input):
    """
    시그모이드 함수
    자연 상수의 지수 함수를 사용한 0~1 사이의 값 출력
    Args:
      input : 입력값
    Return:
      0~1 사이의 값
    """
    x = sympy.Symbol('x')
    result = []

    self.fx = 1/(1+np.e**(-x))

    self.d_fx = sympy.diff(self.fx, x)

    for i in range(input.shape[0]):
      result.append(self.fx.subs([(x, input[i][0])]))

    return np.array(result).reshape(-1, 1)

  def d_sigmoid_fun(self, input):
    """
    시그모이드 함수의 미분값, 노드의 출력이 입력된다.
    arg
      input : 입력값
    return
      시그모이드 미분 함수의 계산 값
    """
    result = []

    x = sympy.Symbol('x')

    for i in range(input.shape[0]):
      result.append(self.d_fx.subs([(x,input[i][0])]))

    return np.array(result).reshape(-1, 1)

오차 함수와 그 미분값의 정의

In [71]:
class Error:
  """
  오차 함수와 오차 함수의 미분 함수를 얻을 수 있다.  
  """
  # 오차 함수
  fx = 0
  
  # 오차 함수의 미분값
  d_fx = 0
  
  def RMSE(self, target, predict):
    """
    일반적인 제곱 오차 함수
    args:
      target : 목표 변수
      predict : 예측 변수
    return:
      제곱 오차 평균 값
    """
    result = (predict - target)**2
    self.result = np.mean(result)

    t = sympy.Symbol('t')
    y = sympy.Symbol('y')

    self.fx = 1/2*((y-t)**2)

    self.d_fx = sympy.diff(self.fx, y)

    return self.result

  def d_RMSE(self, target, predict):
    """
    RMSE 의 미분 함수
    args
      target : 목표 변수
      predict : 예측 변수
    return:
      미분 함수의 계산 값
    """
    result = []

    t = sympy.Symbol('t')
    y = sympy.Symbol('y')

    for i in range(target.shape[0]):
      result.append(self.d_fx.subs([(t, target[i][0]), (y, predict[i][0])]))
    
    return np.array(result).reshape(-1, 1)


In [72]:
class Dense:
  """
  완전 연결층의 계산
  """
  # 가중치 w
  w = []

  # 편향 값 bais
  bias = []

  def cal_dense(self, input, unit, w = [], bias = []):
    """
    args
      input : 입력 데이터
      unit : 은닉층 노드의 개수
    return 
      각 가중치 별 입력 데이터와의 연산 결과
    """
    # 가중치 w의 생성
    if not w:
      w = np.random.rand(input.shape[0], unit)
    
    if not bias:
      bias = np.random.rand()

    self.w.append(w)

    self.bias.append(bias)

    return w.T.dot(input) + bias

In [73]:
class Delta:
  def cal_delta(activation, error):
    return 0

In [74]:
dense = Dense()

In [75]:
hidden_input = dense.cal_dense(input, 3)
hidden_input

array([[47.59187272],
       [28.45064092],
       [34.26519866]])

행의 개수는 입력의 개수, 열은 은닉층의 개수이다.

In [76]:
dense.w

[array([[0.63113348, 0.57498164, 0.3605419 ],
        [0.07980582, 0.99839562, 0.77162014],
        [0.81066848, 0.09121302, 0.1622115 ],
        [0.78716419, 0.1368372 , 0.81220765],
        [0.92282849, 0.35230508, 0.27855203]])]

In [77]:
dense.bias

[0.2277088768265767]

In [78]:
act = Activation()

In [79]:
hidden_input

array([[47.59187272],
       [28.45064092],
       [34.26519866]])

In [80]:
hidden_output = act.sigmoid_fun(hidden_input)
hidden_output

array([[1.00000000000000],
       [0.999999999999559],
       [0.999999999999999]], dtype=object)

In [81]:
result_input = dense.cal_dense(hidden_output, 2)
result_input

array([[1.94768461470366],
       [2.35572345793080]], dtype=object)

In [82]:
result_output = act.sigmoid_fun(result_input)
result_output

array([[0.875193953068249],
       [0.913388084576171]], dtype=object)

In [83]:
err = Error()

In [84]:
result = err.RMSE(target, result_output)

출력층의 델타 계산
오차함수 변화량 * 활성화 함수 변화량

In [85]:
err.d_fx

-1.0*t + 1.0*y

In [86]:
d_err = err.d_RMSE(target, result_output)
d_err

array([[-5.02480604693175],
       [-31.0866119154238]], dtype=object)

In [87]:
act.d_fx

1.0*2.71828182845905**(-x)/(1 + 2.71828182845905**(-x))**2

In [88]:
d_act = act.d_sigmoid_fun(result_output)
d_act

array([[0.207635945438082],
       [0.204335314992613]], dtype=object)

In [89]:
result_delta = d_err * d_act
result_delta

array([[-1.04333035419767],
       [-6.35209263779123]], dtype=object)

은닉층 가중치 변화량의 계산

In [90]:
hidden_output

array([[1.00000000000000],
       [0.999999999999559],
       [0.999999999999999]], dtype=object)

In [91]:
hidden_w_diff = hidden_output * result_delta.T
hidden_w_diff

array([[-1.04333035419767, -6.35209263779123],
       [-1.04333035419721, -6.35209263778843],
       [-1.04333035419767, -6.35209263779122]], dtype=object)

은닉층의 델타 계산

In [92]:
result_delta.shape

(2, 1)

In [93]:
dense.w[1]

array([[0.19441735, 0.83040762],
       [0.55190935, 0.44372727],
       [0.87323673, 0.75346737]])

In [94]:
d_hidden_output = (result_delta.T @ dense.w[1].T).T
d_hidden_output

array([[-5.47766765715545],
       [-3.39442052815990],
       [-5.69716891123862]], dtype=object)

In [95]:
hidden_delta = d_hidden_output * act.d_sigmoid_fun(hidden_output)
hidden_delta

array([[-1.07697482772767],
       [-0.667383582276225],
       [-1.12013139364189]], dtype=object)

In [96]:
input_w_diff = input * hidden_delta.T
input_w_diff

array([[-9.04658855291244, -5.60602209112029, -9.40910370659192],
       [-14.7545551398691, -9.14315507718428, -15.3458000928940],
       [-16.1546224159151, -10.0107537341434, -16.8019709046284],
       [-17.4469922091883, -10.8116140328748, -18.1461285769987],
       [-18.7393620024615, -11.6124743316063, -19.4902862493690]],
      dtype=object)

편향 값에 대한 업데이트

In [99]:
result_delta

array([[-1.04333035419767],
       [-6.35209263779123]], dtype=object)

In [100]:
dense.bias

[0.2277088768265767, 0.3281211931751068]

In [106]:
d_hidden_bias = np.sum(result_delta * dense.bias[1])
d_hidden_bias

-2.42659501616602

In [108]:
hidden_delta

array([[-1.07697482772767],
       [-0.667383582276225],
       [-1.12013139364189]], dtype=object)

In [107]:
d_input_bias = np.sum(hidden_delta * dense.bias[0])
d_input_bias

-0.652269755869364