In [13]:
import numpy as np

입력값과 임의의 타겟값의 지정

In [14]:
data = np.array(([1],[2],[3]))
data

array([[1],
       [2],
       [3]])

In [15]:
target = np.array(([0.5],[0.1]))
target

array([[0.5],
       [0.1]])

임의의 가중치 지정

In [16]:
w1 = np.array(([0.1, 0.2], [0.3, 0.4], [0.5, 0.6]))
w1

array([[0.1, 0.2],
       [0.3, 0.4],
       [0.5, 0.6]])

In [17]:
b1 = np.array(([0.5]))
b1

array([0.5])

In [18]:
w2 = np.array(([0.7, 0.8], [0.9, 0.1]))
w2

array([[0.7, 0.8],
       [0.9, 0.1]])

In [19]:
b2 = np.array(([0.3]))
b2

array([0.3])

순전파의 계산 과정 - 은닉층 입력

In [22]:
hidden_input1 = w1.T @ data + b1
hidden_input1

array([[2.7],
       [3.3]])

순전파의 계산 과정 - 은닉층 출력(활성화 함수 연산-시그모이드 함수)

In [30]:
class activation:
  def sigmoid(self, x):
    return 1 / (1+np.e**-x)

In [33]:
act = activation()

In [34]:
hidden_output1 = act.sigmoid(hidden_input1)
hidden_output1

array([[0.93702664],
       [0.96442881]])

은닉층-출력층까지의 계산(활성화 함수-시그모이드)

In [35]:
hidden_input2 = w2.T @ hidden_output1 + b2
hidden_input2

array([[1.82390458],
       [1.1460642 ]])

In [36]:
hidden_output2 = act.sigmoid(hidden_input2)
hidden_output2

array([[0.86103399],
       [0.75879129]])